#!/usr/bin/env bash
#
# Wikis — one-command installer
# Usage: curl -fsSL https://raw.githubusercontent.com/arozumenko/wikis/main/install.sh | bash
#
set -euo pipefail

REPO="https://github.com/arozumenko/wikis"
INSTALL_DIR="${WIKIS_DIR:-./wikis}"
BRANCH="${WIKIS_BRANCH:-main}"

# ── Colors ──────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
info()  { echo -e "${CYAN}▸${NC} $1"; }
ok()    { echo -e "${GREEN}✓${NC} $1"; }
warn()  { echo -e "${YELLOW}!${NC} $1"; }
err()   { echo -e "${RED}✗${NC} $1" >&2; }
header(){ echo -e "\n${BOLD}$1${NC}"; }

# ── Preflight ───────────────────────────────────────────────────────
header "🔍 Checking prerequisites..."

for cmd in docker git openssl curl; do
  if ! command -v "$cmd" &>/dev/null; then
    err "$cmd is required but not installed."
    exit 1
  fi
done

if ! docker compose version &>/dev/null; then
  err "docker compose (v2) is required. Install Docker Desktop or the compose plugin."
  exit 1
fi

ok "All prerequisites found"

# ── Clone ───────────────────────────────────────────────────────────
header "📦 Setting up Wikis..."

if [ -d "$INSTALL_DIR" ]; then
  warn "Directory $INSTALL_DIR already exists."
  read -rp "   Overwrite? [y/N] " overwrite
  if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
    echo "Aborted."; exit 0
  fi
  rm -rf "$INSTALL_DIR"
fi

info "Cloning repository..."
git clone --depth 1 -b "$BRANCH" "$REPO" "$INSTALL_DIR" 2>/dev/null
cd "$INSTALL_DIR"
ok "Repository cloned to $INSTALL_DIR"

# ── LLM Provider ───────────────────────────────────────────────────
header "🤖 LLM Provider Configuration"

echo ""
echo "  1) OpenAI        (gpt-4o-mini, gpt-4o)"
echo "  2) Anthropic     (claude-sonnet-4-6, claude-haiku-4-5)"
echo "  3) Google Gemini (gemini-2.5-pro, gemini-2.0-flash)"
echo "  4) Ollama        (local, no API key needed)"
echo "  5) Skip          (configure later in .env)"
echo ""
read -rp "Choose provider [1-5]: " provider_choice

LLM_PROVIDER=""
LLM_API_KEY=""
LLM_MODEL=""
EMBEDDING_MODEL=""

case "${provider_choice:-1}" in
  1)
    LLM_PROVIDER="openai"
    LLM_MODEL="gpt-4o-mini"
    EMBEDDING_MODEL="text-embedding-3-large"
    read -rp "OpenAI API key: " LLM_API_KEY
    ;;
  2)
    LLM_PROVIDER="anthropic"
    LLM_MODEL="claude-sonnet-4-6"
    EMBEDDING_MODEL="text-embedding-3-large"
    read -rp "Anthropic API key: " LLM_API_KEY
    warn "Anthropic doesn't provide embeddings — set OPENAI_API_KEY in .env for embeddings, or use Ollama."
    ;;
  3)
    LLM_PROVIDER="gemini"
    LLM_MODEL="gemini-2.5-pro"
    EMBEDDING_MODEL="models/text-embedding-004"
    read -rp "Google AI API key: " LLM_API_KEY
    ;;
  4)
    LLM_PROVIDER="ollama"
    LLM_MODEL="llama3.2"
    EMBEDDING_MODEL="nomic-embed-text"
    LLM_API_KEY="not-needed"
    info "Make sure Ollama is running: ollama pull llama3.2 && ollama pull nomic-embed-text"
    ;;
  5)
    info "Skipping LLM config — edit .env before starting."
    ;;
  *)
    warn "Invalid choice, defaulting to OpenAI."
    LLM_PROVIDER="openai"
    LLM_MODEL="gpt-4o-mini"
    EMBEDDING_MODEL="text-embedding-3-large"
    read -rp "OpenAI API key: " LLM_API_KEY
    ;;
esac

# ── Generate JWT keys ──────────────────────────────────────────────
header "🔐 Generating authentication keys..."

KEYS_DIR="$(pwd)/.keys"
mkdir -p "$KEYS_DIR"
openssl genrsa -out "$KEYS_DIR/private.pem" 2048 2>/dev/null
openssl rsa -in "$KEYS_DIR/private.pem" -pubout -out "$KEYS_DIR/public.pem" 2>/dev/null

JWT_PRIVATE_KEY=$(cat "$KEYS_DIR/private.pem")
JWT_PUBLIC_KEY=$(cat "$KEYS_DIR/public.pem")
AUTH_SECRET=$(openssl rand -hex 32)

ok "RS256 key pair generated"

# ── Write .env ─────────────────────────────────────────────────────
header "📝 Writing configuration..."

cat > .env <<ENVFILE
# ═══════════════════════════════════════════════════════════════════
# Wikis Configuration — generated by install.sh
# ═══════════════════════════════════════════════════════════════════

# LLM
LLM_PROVIDER=${LLM_PROVIDER}
LLM_API_KEY=${LLM_API_KEY}
LLM_MODEL=${LLM_MODEL}
EMBEDDING_MODEL=${EMBEDDING_MODEL}

# Storage
STORAGE_BACKEND=local
STORAGE_PATH=/app/data/artifacts
CACHE_DIR=/app/data/cache

# Auth
NEXTAUTH_URL=http://localhost:3000
AUTH_SECRET=${AUTH_SECRET}
# Uncomment to enable OAuth:
# GITHUB_CLIENT_ID=
# GITHUB_CLIENT_SECRET=
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=

# JWT (cross-service auth)
JWT_PRIVATE_KEY="${JWT_PRIVATE_KEY}"
JWT_PUBLIC_KEY="${JWT_PUBLIC_KEY}"

# Internal
BACKEND_URL=http://backend:8000
WIKIS_BACKEND_URL=http://localhost:8000
LOG_LEVEL=INFO
NODE_ENV=production
ENVFILE

ok "Configuration written to .env"

# ── Start services ─────────────────────────────────────────────────
header "🚀 Starting Wikis..."

docker compose pull 2>/dev/null || true
docker compose up -d

info "Waiting for services to be healthy..."
attempt=0
max_attempts=30
while [ $attempt -lt $max_attempts ]; do
  if curl -sf http://localhost:3000 >/dev/null 2>&1; then
    break
  fi
  attempt=$((attempt + 1))
  sleep 2
done

if [ $attempt -eq $max_attempts ]; then
  warn "Services are still starting. Check: docker compose ps"
else
  ok "Services are running"
fi

# ── Done ────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}═══════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  Wikis is ready!${NC}"
echo -e "${GREEN}${BOLD}═══════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BOLD}App:${NC}       http://localhost:3000"
echo -e "  ${BOLD}API:${NC}       http://localhost:8000/docs"
echo -e "  ${BOLD}Login:${NC}     admin@wikis.dev / changeme123"
echo ""
echo -e "  ${YELLOW}Change the default password after first login.${NC}"
echo ""
echo -e "  Manage:  cd $INSTALL_DIR"
echo -e "           docker compose ps      # status"
echo -e "           docker compose logs -f  # logs"
echo -e "           docker compose down     # stop"
echo ""
