/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Wiki */
        post: operations["generate_wiki_api_v1_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invocations/{invocation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Invocation */
        get: operations["get_invocation_api_v1_invocations__invocation_id__get"];
        put?: never;
        post?: never;
        /** Cancel Invocation */
        delete: operations["cancel_invocation_api_v1_invocations__invocation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invocations/{invocation_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Invocation */
        get: operations["stream_invocation_api_v1_invocations__invocation_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_v1_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research */
        post: operations["research_api_v1_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Wikis */
        get: operations["list_wikis_api_v1_wikis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Wiki */
        post: operations["resume_wiki_api_v1_wikis__wiki_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Wiki */
        post: operations["refresh_wiki_api_v1_wikis__wiki_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Wiki */
        delete: operations["delete_wiki_api_v1_wikis__wiki_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AskRequest
         * @description Request to ask a question about a wiki.
         */
        AskRequest: {
            /** Wiki Id */
            wiki_id: string;
            /** Question */
            question: string;
            /** Chat History */
            chat_history?: components["schemas"]["ChatMessage"][];
            /**
             * K
             * @default 15
             */
            k: number;
        };
        /**
         * AskResponse
         * @description Response to an ask question.
         */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
        };
        /**
         * ChatMessage
         * @description A single chat message.
         */
        ChatMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /**
         * DeleteWikiResponse
         * @description Response after deleting a wiki.
         */
        DeleteWikiResponse: {
            /** Deleted */
            deleted: boolean;
            /** Wiki Id */
            wiki_id: string;
        };
        /**
         * ErrorResponse
         * @description Standard error response.
         */
        ErrorResponse: {
            /** Error */
            error: string;
            /**
             * Detail
             * @default null
             */
            detail: string | null;
            /** Code */
            code: string;
        };
        /**
         * GenerateWikiRequest
         * @description Request to generate a wiki from a repository.
         */
        GenerateWikiRequest: {
            /** Repo Url */
            repo_url: string;
            /**
             * Branch
             * @default main
             */
            branch: string;
            /**
             * Provider
             * @default github
             */
            provider: string;
            /**
             * Access Token
             * @default null
             */
            access_token: string | null;
            /**
             * Wiki Title
             * @default null
             */
            wiki_title: string | null;
            /**
             * Include Research
             * @default true
             */
            include_research: boolean;
            /**
             * Include Diagrams
             * @default true
             */
            include_diagrams: boolean;
            /**
             * Force Rebuild Index
             * @default true
             */
            force_rebuild_index: boolean;
            /**
             * Llm Model
             * @default null
             */
            llm_model: string | null;
            /**
             * Embedding Model
             * @default null
             */
            embedding_model: string | null;
            /**
             * Visibility
             * @default personal
             */
            visibility?: 'personal' | 'shared';
            /**
             * Planner Type
             * @description Structure planner override (agent or cluster). Null falls back to server config.
             * @default null
             */
            planner_type?: 'agent' | 'cluster' | null;
            /**
             * Exclude Tests
             * @description When true, soft-skip test nodes during clustering. Null falls back to server config.
             * @default null
             */
            exclude_tests?: boolean | null;
        };
        /**
         * GenerateWikiResponse
         * @description Response after initiating wiki generation.
         */
        GenerateWikiResponse: {
            /** Wiki Id */
            wiki_id: string;
            /** Invocation Id */
            invocation_id: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Services */
            services?: {
                [key: string]: string;
            };
        };
        /**
         * Invocation
         * @description Tracks the state of a background wiki generation job.
         */
        Invocation: {
            /** Id */
            id: string;
            /** Wiki Id */
            wiki_id: string;
            /**
             * Status
             * @default generating
             */
            status: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Current Phase
             * @default
             */
            current_phase: string;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Completed At */
            completed_at?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Pages Completed
             * @default 0
             */
            pages_completed: number;
            /** Pages Total */
            pages_total?: number | null;
            /** Estimated Tokens */
            estimated_tokens?: number | null;
            /** Model Context Limit */
            model_context_limit?: number | null;
        };
        /**
         * ResearchRequest
         * @description Request to perform deep research on a wiki.
         */
        ResearchRequest: {
            /** Wiki Id */
            wiki_id: string;
            /** Question */
            question: string;
            /**
             * Research Type
             * @default general
             */
            research_type: string;
            /**
             * Enable Subagents
             * @default true
             */
            enable_subagents: boolean;
        };
        /**
         * ResearchResponse
         * @description Response from deep research.
         */
        ResearchResponse: {
            /** Answer */
            answer: string;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Research Steps */
            research_steps?: string[];
        };
        /**
         * SourceReference
         * @description A reference to a source code location.
         */
        SourceReference: {
            /** File Path */
            file_path: string;
            /**
             * Line Start
             * @default null
             */
            line_start: number | null;
            /**
             * Line End
             * @default null
             */
            line_end: number | null;
            /**
             * Snippet
             * @default null
             */
            snippet: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WikiListResponse
         * @description Response listing all wikis.
         */
        WikiListResponse: {
            /** Wikis */
            wikis?: components["schemas"]["WikiSummary"][];
        };
        /**
         * WikiSummary
         * @description Summary of a generated wiki.
         */
        WikiSummary: {
            /** Wiki Id */
            wiki_id: string;
            /** Repo Url */
            repo_url: string;
            /** Branch */
            branch: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Page Count */
            page_count: number;
            /**
             * Status
             * @default complete
             */
            status: string;
            /**
             * Progress
             * @default 1
             */
            progress: number;
            /**
             * Invocation Id
             * @default null
             */
            invocation_id: string | null;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Owner Id
             * @default null
             */
            owner_id?: string | null;
            /**
             * Visibility
             * @default personal
             */
            visibility?: 'personal' | 'shared';
            /**
             * Is Owner
             * @default true
             */
            is_owner?: boolean;
        };
        /**
         * SSEEvent
         * @description Generic SSE event wrapper.
         */
        SSEEvent: {
            /** Event */
            event: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /**
         * ProgressEvent
         * @description Progress update during wiki generation.
         */
        ProgressEvent: {
            /**
             * Event
             * @default progress
             */
            event: string;
            /** Phase */
            phase: string;
            /** Progress */
            progress: number;
            /** Message */
            message: string;
            /**
             * Page Id
             * @default null
             */
            page_id: string | null;
        };
        /**
         * PageCompleteEvent
         * @description Fired when a single wiki page finishes generating.
         */
        PageCompleteEvent: {
            /**
             * Event
             * @default page_complete
             */
            event: string;
            /** Page Id */
            page_id: string;
            /** Page Title */
            page_title: string;
        };
        /**
         * WikiCompleteEvent
         * @description Fired when the entire wiki generation is done.
         */
        WikiCompleteEvent: {
            /**
             * Event
             * @default wiki_complete
             */
            event: string;
            /** Wiki Id */
            wiki_id: string;
            /** Page Count */
            page_count: number;
            /** Execution Time */
            execution_time: number;
        };
        /**
         * ErrorEvent
         * @description Fired on error during generation.
         */
        ErrorEvent: {
            /**
             * Event
             * @default error
             */
            event: string;
            /** Error */
            error: string;
            /**
             * Recoverable
             * @default false
             */
            recoverable: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    generate_wiki_api_v1_generate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateWikiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateWikiResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_invocation_api_v1_invocations__invocation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                invocation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invocation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_invocation_api_v1_invocations__invocation_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                invocation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_invocation_api_v1_invocations__invocation_id__stream_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                invocation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_v1_ask_post: {
        parameters: {
            query?: {
                accept?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_api_v1_research_post: {
        parameters: {
            query?: {
                accept?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_wikis_api_v1_wikis_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_wiki_api_v1_wikis__wiki_id__resume_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateWikiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_wiki_api_v1_wikis__wiki_id__refresh_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateWikiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_wiki_api_v1_wikis__wiki_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteWikiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
