/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Wiki */
        post: operations["generate_wiki_api_v1_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Wikis */
        get: operations["list_wikis_api_v1_wikis_get"];
        put?: never;
        /** Generate Wiki */
        post: operations["generate_wiki_api_v1_wikis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Source
         * @description Validate a source configuration and return a preview.
         *
         *     Drives Step 3 (Scan) of the ingestion wizard (#208). Persists nothing:
         *     no ``WikiRecord``, no invocation registration, no token write. The
         *     response carries reachability + a connector-specific preview shape.
         *
         *     All three source types are supported: ``git``, ``confluence``, ``jira``.
         *
         *     Request shape: ``source_type`` is **required** — it discriminates the
         *     typed scope/auth variants (#215). Callers must include it explicitly;
         *     omitting it returns 422 (Pydantic ``union_tag_not_found``). Pre-#215
         *     callers that relied on the implicit ``"git"`` default need to update.
         *
         *     Errors (no ``responses=`` declaration intentionally — the 400 body
         *     doesn't match :class:`ErrorResponse`'s top-level shape and the SPA
         *     codegen would otherwise produce wrong client types.):
         *
         *     * ``400`` — ``{"detail": {"error": <message>, "reachable": <bool>}}``
         *       for unreachable / auth-fail / invalid-scope / invalid-JQL.
         *     * ``422`` — Pydantic validation error: ``source_type`` missing or not
         *       ``"git"`` / ``"confluence"`` / ``"jira"``, or per-variant field
         *       validation failed.
         *
         *     TODO(follow-up): rate-limit / tmpdir-exhaustion guard. A malicious
         *     authenticated user can fan out concurrent scans; each shallow clone
         *     creates a tmpdir for the context-manager lifetime. Belongs at the
         *     gateway / network policy layer rather than in this handler.
         */
        post: operations["scan_source_api_v1_sources_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invocations/{invocation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Invocation */
        get: operations["get_invocation_api_v1_invocations__invocation_id__get"];
        put?: never;
        post?: never;
        /** Cancel Invocation */
        delete: operations["cancel_invocation_api_v1_invocations__invocation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invocations/{invocation_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Invocation */
        get: operations["stream_invocation_api_v1_invocations__invocation_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_v1_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research */
        post: operations["research_api_v1_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wiki
         * @description Get wiki detail with pages and their content.
         */
        get: operations["get_wiki_api_v1_wikis__wiki_id__get"];
        put?: never;
        post?: never;
        /** Delete Wiki */
        delete: operations["delete_wiki_api_v1_wikis__wiki_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Wiki
         * @description Full-text search over wiki pages with graph-expansion re-ranking.
         */
        get: operations["search_wiki_api_v1_wikis__wiki_id__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Wiki Pages
         * @description List all pages in a wiki with their titles and descriptions.
         */
        get: operations["list_wiki_pages_api_v1_wikis__wiki_id__pages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/pages/{page_title}/neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Page Neighbors
         * @description Return the wikilink graph neighborhood for a single wiki page.
         */
        get: operations["get_page_neighbors_api_v1_wikis__wiki_id__pages__page_title__neighbors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/pages/{page_title}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wiki Page By Title
         * @description Return the full content of a single wiki page identified by its title.
         */
        get: operations["get_wiki_page_by_title_api_v1_wikis__wiki_id__pages__page_title__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/pages/{page_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wiki Page
         * @description Get a single wiki page content. page_id can be section/page format.
         */
        get: operations["get_wiki_page_api_v1_wikis__wiki_id__pages__page_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Wiki */
        post: operations["resume_wiki_api_v1_wikis__wiki_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/qa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Qa
         * @description Paginated Q&A history for a wiki.
         */
        get: operations["list_qa_api_v1_wikis__wiki_id__qa_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/qa/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Qa Stats
         * @description QA statistics for a wiki.
         */
        get: operations["qa_stats_api_v1_wikis__wiki_id__qa_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Wiki */
        post: operations["refresh_wiki_api_v1_wikis__wiki_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diff Wiki
         * @description Diff a fresh-parse payload against the indexed snapshot.
         *
         *     The caller supplies the freshly parsed nodes (id + content_hash + path);
         *     the server compares them against the wiki's stored ``repo_nodes`` and
         *     returns the resulting change set plus the wiki pages those changes
         *     touch (via the ``page_symbols`` reverse index from #116 PR 1).
         *
         *     Read-only: no parsing, no LLM, no writes. PR 3 will wire the actual
         *     re-parse loop on top of this primitive.
         */
        post: operations["diff_wiki_api_v1_wikis__wiki_id__diff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/incremental-refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Incremental Refresh Wiki
         * @description Trigger an incremental refresh on a previously-generated wiki.
         *
         *     The caller supplies pre-parsed nodes (same shape as ``/diff``).
         *     The server diffs them against the indexed snapshot, dispatches each
         *     affected page through the trivial / edit / structural regimes, and
         *     streams progress over SSE.
         *
         *     Owner-only — same access model as ``/refresh`` since this surfaces
         *     internal content_hash + node_id state through the per-page events.
         */
        post: operations["incremental_refresh_wiki_api_v1_wikis__wiki_id__incremental_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Wiki Visibility
         * @description Change a wiki's visibility between 'personal' and 'shared'.
         */
        patch: operations["update_wiki_visibility_api_v1_wikis__wiki_id__visibility_patch"];
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Wiki Description
         * @description Update the user-provided description for a wiki.
         */
        patch: operations["update_wiki_description_api_v1_wikis__wiki_id__description_patch"];
        trace?: never;
    };
    "/api/v1/wikis/{wiki_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Wiki
         * @description Export a wiki as a downloadable ZIP archive.
         *
         *     Supports two formats:
         *     - ``obsidian`` — Obsidian vault layout with YAML frontmatter
         *     - ``wikis`` — Wikis-to-Wikis bundle for re-importing into another instance
         */
        get: operations["export_wiki_api_v1_wikis__wiki_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikis/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Wiki
         * @description Import a wiki from a ``.wikiexport`` bundle produced by the wikis export.
         */
        post: operations["import_wiki_api_v1_wikis_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/wikis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Wikis */
        get: operations["list_project_wikis_api_v1_projects__project_id__wikis_get"];
        put?: never;
        /** Add Wiki To Project */
        post: operations["add_wiki_to_project_api_v1_projects__project_id__wikis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/wikis/{wiki_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Wiki From Project */
        delete: operations["remove_wiki_from_project_api_v1_projects__project_id__wikis__wiki_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recompute Project Route
         * @description Stream a project-level recompute (relatedness → cross-repo → leiden).
         *
         *     Gated server-side by ``flags.project_graph``. Emits SSE progress events
         *     matching the wiki-generation widget contract.
         */
        post: operations["recompute_project_route_api_v1_projects__project_id__recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Project
         * @description Full-text search over all wiki pages in a project with graph-expansion re-ranking.
         */
        get: operations["search_project_api_v1_projects__project_id__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Project Codemap
         * @description Build a code-map for all wikis in a project.
         *
         *     Proxies to the codemap pipeline with ``project_id`` set and
         *     ``research_type=codemap``.
         */
        post: operations["project_codemap_api_v1_projects__project_id__map_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AffectedPageResponse
         * @description One wiki page touched by the change set.
         */
        AffectedPageResponse: {
            /** Page Id */
            page_id: string;
            /** Title */
            title?: string | null;
            /** Anchor Slug */
            anchor_slug?: string | null;
            /** Changes */
            changes?: components["schemas"]["NodeChangeResponse"][];
        };
        /**
         * AskRequest
         * @description Request to ask a question about a wiki.
         */
        AskRequest: {
            /**
             * Wiki Id
             * @default null
             */
            wiki_id: string | null;
            /**
             * Project Id
             * @default null
             */
            project_id: string | null;
            /** Question */
            question: string;
            /** Chat History */
            chat_history?: components["schemas"]["ChatMessage"][];
            /**
             * K
             * @default 15
             */
            k: number;
            /**
             * Min Confidence
             * @default null
             */
            min_confidence: string | null;
        };
        /**
         * AskResponse
         * @description Response to an ask question.
         */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /**
             * Tool Steps
             * @default 0
             */
            tool_steps: number;
            /**
             * Qa Id
             * @default
             */
            qa_id: string;
        };
        /**
         * AtlassianAuth
         * @description Auth for Confluence or Jira (OAuth2 access token + optional refresh).
         *
         *     ``extra="forbid"`` ensures that GitAuth fields (e.g. ``pat``) are rejected
         *     when paired with ``source_type="confluence"`` or ``source_type="jira"``.
         */
        AtlassianAuth: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token?: string | null;
            /** Client Id */
            client_id?: string | null;
        };
        /** Body_import_wiki_api_v1_wikis_import_post */
        Body_import_wiki_api_v1_wikis_import_post: {
            /** Bundle */
            bundle: string;
        };
        /**
         * CallStack
         * @description A named call-flow chain, e.g. 'Frontend Auth' or 'MCP Auth'.
         */
        CallStack: {
            /** Title */
            title: string;
            /** Steps */
            steps?: components["schemas"]["CallStackStep"][];
        };
        /**
         * CallStackStep
         * @description One step in a call stack chain.
         */
        CallStackStep: {
            /** Symbol */
            symbol: string;
            /**
             * File Path
             * @default
             */
            file_path: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * ChangeSetResponse
         * @description Aggregate change set — one entry per kind.
         */
        ChangeSetResponse: {
            /** Added */
            added?: components["schemas"]["NodeChangeResponse"][];
            /** Modified */
            modified?: components["schemas"]["NodeChangeResponse"][];
            /** Moved */
            moved?: components["schemas"]["NodeChangeResponse"][];
            /** Deleted */
            deleted?: components["schemas"]["NodeChangeResponse"][];
            /** Total */
            total: number;
        };
        /**
         * ChatMessage
         * @description A single chat message.
         */
        ChatMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /**
         * CodeMapData
         * @description Hierarchical call-tree for the code-map right panel.
         */
        CodeMapData: {
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Call Stacks */
            call_stacks?: components["schemas"]["CallStack"][];
            /** Sections */
            sections?: components["schemas"]["CodeMapSection"][];
        };
        /**
         * CodeMapSection
         * @description A top-level section in the call-tree (usually one source file).
         */
        CodeMapSection: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * File Path
             * @default
             */
            file_path: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Symbols */
            symbols?: components["schemas"]["CodeMapSymbol"][];
        };
        /**
         * CodeMapSymbol
         * @description A single symbol (function / class / variable) shown as a leaf in the tree.
         */
        CodeMapSymbol: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Symbol Type
             * @default
             */
            symbol_type: string;
            /**
             * File Path
             * @default
             */
            file_path: string;
            /**
             * Line Start
             * @default null
             */
            line_start: number | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Relationships */
            relationships?: string[];
        };
        /**
         * ConfluenceScanPreview
         * @description Preview returned for ``source_type == "confluence"``.
         *
         *     ``page_count`` on each space is the total returned by the Confluence API
         *     for that space.  When the API paginates without a total-results field,
         *     ``page_count`` is left as ``None`` and the caller should render it as
         *     ``"?"``.
         */
        ConfluenceScanPreview: {
            /** Spaces */
            spaces: components["schemas"]["ConfluenceSpaceInfo"][];
            /** Total Pages */
            total_pages?: number | null;
        };
        /**
         * ConfluenceScanRequest
         * @description Scan request for a Confluence instance.
         */
        ConfluenceScanRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "confluence";
            scope: components["schemas"]["ConfluenceScope"];
            auth: components["schemas"]["AtlassianAuth"];
        };
        /**
         * ConfluenceScope
         * @description Scope for a Confluence source.
         */
        ConfluenceScope: {
            /** Base Url */
            base_url: string;
            /** Space Keys */
            space_keys?: string[];
        };
        /**
         * ConfluenceSpaceInfo
         * @description Per-space summary inside a :class:`ConfluenceScanPreview`.
         */
        ConfluenceSpaceInfo: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Page Count */
            page_count?: number | null;
        };
        /**
         * DeleteWikiResponse
         * @description Response after deleting a wiki.
         */
        DeleteWikiResponse: {
            /** Deleted */
            deleted: boolean;
            /** Wiki Id */
            wiki_id: string;
            /**
             * Message
             * @default null
             */
            message: string | null;
        };
        /**
         * DiffWikiRequest
         * @description Body for ``POST /wikis/{wiki_id}/diff`` — supply the freshly parsed
         *     nodes; the server diffs them against the indexed snapshot.
         *
         *     Capped at 50 000 nodes per request to bound the cost of the per-node
         *     reverse-index lookup. The largest repos in our corpus parse to ~30k
         *     architectural nodes; 50k gives ~1.5x headroom before PR 3 swaps in the
         *     batched ``get_pages_citing_nodes`` query.
         */
        DiffWikiRequest: {
            /** Parsed Nodes */
            parsed_nodes?: components["schemas"]["ParsedNodeInput"][];
        };
        /**
         * DiffWikiResponse
         * @description Result of the diff endpoint — no writes occur.
         */
        DiffWikiResponse: {
            /** Wiki Id */
            wiki_id: string;
            change_set: components["schemas"]["ChangeSetResponse"];
            /** Affected Pages */
            affected_pages?: components["schemas"]["AffectedPageResponse"][];
        };
        /**
         * ErrorResponse
         * @description Standard error response.
         */
        ErrorResponse: {
            /** Error */
            error: string;
            /**
             * Detail
             * @default null
             */
            detail: string | null;
            /** Code */
            code: string;
        };
        /**
         * GenerateWikiRequest
         * @description Request to generate a wiki from a repository or Atlassian source.
         *
         *     Preferred (new) shape
         *     ---------------------
         *     source_type + scope + auth — see module docstring for field shapes.
         *
         *     Backwards-compatible (legacy) shape
         *     ------------------------------------
         *     repo_url + branch + access_token — auto-normalized into the new shape
         *     by the ``_normalize_legacy`` validator so old callers keep working.
         */
        GenerateWikiRequest: {
            /**
             * Source Type
             * @default git
             * @enum {string}
             */
            source_type: "git" | "confluence" | "jira";
            /** Scope */
            scope?: {
                [key: string]: unknown;
            };
            /** Auth */
            auth?: {
                [key: string]: unknown;
            };
            /**
             * Repo Url
             * @default null
             */
            repo_url: string | null;
            /**
             * Branch
             * @default null
             */
            branch: string | null;
            /**
             * Provider
             * @default github
             */
            provider: string;
            /**
             * Access Token
             * @default null
             */
            access_token: string | null;
            /**
             * Wiki Title
             * @default null
             */
            wiki_title: string | null;
            /**
             * Include Research
             * @default true
             */
            include_research: boolean;
            /**
             * Include Diagrams
             * @default true
             */
            include_diagrams: boolean;
            /**
             * Force Rebuild Index
             * @default true
             */
            force_rebuild_index: boolean;
            /**
             * Visibility
             * @default personal
             */
            visibility: string;
            /**
             * Llm Model
             * @default null
             */
            llm_model: string | null;
            /**
             * Embedding Model
             * @default null
             */
            embedding_model: string | null;
            /**
             * Structure Planner
             * @default null
             */
            structure_planner: ("agentic" | "graph_clustering") | null;
            /**
             * Planner Type
             * @default null
             */
            planner_type: ("agent" | "cluster") | null;
            /**
             * Exclude Tests
             * @default null
             */
            exclude_tests: boolean | null;
        };
        /**
         * GenerateWikiResponse
         * @description Response after initiating wiki generation.
         */
        GenerateWikiResponse: {
            /** Wiki Id */
            wiki_id: string;
            /** Invocation Id */
            invocation_id: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /**
         * GitAuth
         * @description Auth for a git source (optional PAT).
         *
         *     ``extra="forbid"`` ensures that AtlassianAuth fields (e.g. ``access_token``)
         *     are rejected when paired with ``source_type="git"``, making the discriminated
         *     union enforce valid combos at validation time.
         */
        GitAuth: {
            /** Pat */
            pat?: string | null;
        };
        /**
         * GitScanPreview
         * @description Preview returned for ``source_type == "git"``.
         */
        GitScanPreview: {
            /** Default Branch */
            default_branch?: string | null;
            /** Resolved Branch */
            resolved_branch: string;
            /** Commit Hash */
            commit_hash?: string | null;
            /** File Count */
            file_count: number;
            /** Top Paths */
            top_paths: string[];
            /** Size Bytes */
            size_bytes: number;
        };
        /**
         * GitScanRequest
         * @description Scan request for a git repository.
         */
        GitScanRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "git";
            scope: components["schemas"]["GitScope"];
            auth?: components["schemas"]["GitAuth"];
        };
        /**
         * GitScope
         * @description Scope for a git source.
         */
        GitScope: {
            /** Repo Url */
            repo_url: string;
            /**
             * Branch
             * @default main
             */
            branch: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Services */
            services?: {
                [key: string]: string;
            };
        };
        /**
         * IncrementalRefreshRequest
         * @description POST ``/wikis/{id}/incremental-refresh`` body.
         *
         *     Caller supplies pre-parsed nodes (same shape as ``/diff``). Capped at
         *     50_000 nodes per request to bound the orchestrator's snapshot work.
         */
        IncrementalRefreshRequest: {
            /** Parsed Nodes */
            parsed_nodes?: components["schemas"]["ParsedNodeInput"][];
        };
        /**
         * IncrementalRefreshResponse
         * @description Initial response — actual progress flows over SSE.
         *
         *     The orchestrator runs asynchronously after this returns; subscribe
         *     to ``/invocations/{invocation_id}/stream`` for ``page_unchanged``,
         *     ``page_patched``, ``page_edited``, ``page_regenerated``, and the
         *     final ``incremental_summary`` event with the run stats.
         */
        IncrementalRefreshResponse: {
            /** Wiki Id */
            wiki_id: string;
            /** Invocation Id */
            invocation_id: string;
            /** Status */
            status: string;
            /** Page Count */
            page_count: number;
            /** Message */
            message?: string | null;
        };
        /**
         * Invocation
         * @description Tracks the state of a background wiki generation job.
         */
        Invocation: {
            /** Id */
            id: string;
            /** Wiki Id */
            wiki_id: string;
            /**
             * Repo Url
             * @default
             */
            repo_url: string;
            /**
             * Branch
             * @default
             */
            branch: string;
            /**
             * Owner Id
             * @default
             */
            owner_id: string;
            /**
             * Status
             * @default generating
             */
            status: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Current Phase
             * @default
             */
            current_phase: string;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Completed At */
            completed_at?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Pages Completed
             * @default 0
             */
            pages_completed: number;
            /** Pages Total */
            pages_total?: number | null;
            /** Estimated Tokens */
            estimated_tokens?: number | null;
            /** Model Context Limit */
            model_context_limit?: number | null;
        };
        /**
         * JiraScanPreview
         * @description Preview returned for ``source_type == "jira"``.
         */
        JiraScanPreview: {
            /** Matching Issues */
            matching_issues: number;
            /** Sample Issue Keys */
            sample_issue_keys: string[];
            /** Jql Validated */
            jql_validated: boolean;
        };
        /**
         * JiraScanRequest
         * @description Scan request for a Jira instance.
         */
        JiraScanRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "jira";
            scope: components["schemas"]["JiraScope"];
            auth: components["schemas"]["AtlassianAuth"];
        };
        /**
         * JiraScope
         * @description Scope for a Jira source.
         */
        JiraScope: {
            /** Base Url */
            base_url: string;
            /** Jql */
            jql: string;
        };
        /**
         * NodeChangeResponse
         * @description One change in the response. Field population depends on ``kind``.
         */
        NodeChangeResponse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "added" | "modified" | "deleted" | "moved";
            /** Node Id */
            node_id: string;
            /** Old Hash */
            old_hash?: string | null;
            /** New Hash */
            new_hash?: string | null;
            /** Old Path */
            old_path?: string | null;
            /** New Path */
            new_path?: string | null;
        };
        /**
         * PageListItem
         * @description A brief description of a single wiki page, used in list responses.
         */
        PageListItem: {
            /** Page Title */
            page_title: string;
            /** Description */
            description: string;
            /** Section */
            section?: string | null;
        };
        /**
         * PageNeighbor
         * @description A neighboring wiki page with its relationship direction.
         */
        PageNeighbor: {
            /** Title */
            title: string;
            /**
             * Rel
             * @enum {string}
             */
            rel: "links_to" | "linked_from";
        };
        /**
         * PageNeighborsResponse
         * @description Response containing the neighbor graph for a single wiki page.
         */
        PageNeighborsResponse: {
            /** Wiki Id */
            wiki_id: string;
            /** Page Title */
            page_title: string;
            /** Links To */
            links_to: string[];
            /** Linked From */
            linked_from: string[];
        };
        /**
         * ParsedNodeInput
         * @description One node from a fresh parse, supplied to the diff endpoint.
         *
         *     Only the three fields needed for change classification are required;
         *     callers can pass the same dicts they would otherwise hand to
         *     ``upsert_nodes_batch`` (extra keys are ignored).
         */
        ParsedNodeInput: {
            /** Node Id */
            node_id: string;
            /** Content Hash */
            content_hash?: string | null;
            /**
             * Rel Path
             * @default
             */
            rel_path: string;
        };
        /**
         * ProjectAddWikiRequest
         * @description Request to add a wiki to a project.
         */
        ProjectAddWikiRequest: {
            /** Wiki Id */
            wiki_id: string;
        };
        /**
         * ProjectCreateRequest
         * @description Request to create a new project.
         */
        ProjectCreateRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Visibility
             * @default personal
             * @enum {string}
             */
            visibility: "personal" | "shared";
        };
        /**
         * ProjectListResponse
         * @description Response listing all projects.
         */
        ProjectListResponse: {
            /** Projects */
            projects: components["schemas"]["ProjectResponse"][];
        };
        /**
         * ProjectResponse
         * @description Response for a single project.
         */
        ProjectResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Visibility */
            visibility: string;
            /** Owner Id */
            owner_id: string;
            /**
             * Is Owner
             * @default false
             */
            is_owner: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Wiki Count
             * @default 0
             */
            wiki_count: number;
        };
        /**
         * ProjectSearchResponse
         * @description Response for a search scoped to all wikis in a project.
         */
        ProjectSearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchResultItem"][];
            /** Wiki Summary */
            wiki_summary: components["schemas"]["WikiSummaryItem"][];
        };
        /**
         * ProjectUpdateRequest
         * @description Request to update an existing project.
         */
        ProjectUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Visibility */
            visibility?: ("personal" | "shared") | null;
        };
        /**
         * QAListResponse
         * @description Paginated QA list response.
         */
        QAListResponse: {
            /** Items */
            items: components["schemas"]["QARecordResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * QARecordResponse
         * @description Single QA record in API responses.
         */
        QARecordResponse: {
            /** Id */
            id: string;
            /** Wiki Id */
            wiki_id: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Sources Json */
            sources_json?: string | null;
            /**
             * Tool Steps
             * @default 0
             */
            tool_steps: number;
            /**
             * Mode
             * @default fast
             * @enum {string}
             */
            mode: "fast" | "deep";
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "validated" | "rejected" | "enriched" | "stale";
            /**
             * Is Cache Hit
             * @default false
             */
            is_cache_hit: boolean;
            /**
             * Has Context
             * @default false
             */
            has_context: boolean;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * QAStatsResponse
         * @description QA statistics response.
         */
        QAStatsResponse: {
            /** Total Count */
            total_count: number;
            /** Cache Hit Count */
            cache_hit_count: number;
            /** Validated Count */
            validated_count: number;
            /** Rejected Count */
            rejected_count: number;
            /** Hit Rate */
            hit_rate: number;
        };
        /**
         * RefreshWikiRequest
         * @description Request body for wiki refresh — allows passing an access token for private repos.
         */
        RefreshWikiRequest: {
            /** Access Token */
            access_token?: string | null;
        };
        /**
         * ResearchRequest
         * @description Request to perform deep research on a wiki.
         */
        ResearchRequest: {
            /**
             * Wiki Id
             * @default null
             */
            wiki_id: string | null;
            /**
             * Project Id
             * @default null
             */
            project_id: string | null;
            /** Question */
            question: string;
            /**
             * Research Type
             * @default general
             */
            research_type: string;
            /** Chat History */
            chat_history?: components["schemas"]["ChatMessage"][];
        };
        /**
         * ResearchResponse
         * @description Response from deep research.
         */
        ResearchResponse: {
            /** Answer */
            answer: string;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Research Steps */
            research_steps?: string[];
            /** @default null */
            code_map: components["schemas"]["CodeMapData"] | null;
        };
        /**
         * ScanResponse
         * @description Result of a source scan. ``preview`` shape varies by ``source_type``.
         */
        ScanResponse: {
            /** Source Type */
            source_type: string;
            /** Reachable */
            reachable: boolean;
            /** Preview */
            preview?: components["schemas"]["GitScanPreview"] | components["schemas"]["ConfluenceScanPreview"] | components["schemas"]["JiraScanPreview"] | null;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * SearchResultItem
         * @description A single search result item from a wiki page.
         */
        SearchResultItem: {
            /** Wiki Id */
            wiki_id: string;
            /** Wiki Name */
            wiki_name: string;
            /** Page Title */
            page_title: string;
            /** Snippet */
            snippet: string;
            /** Score */
            score: number;
            /** Neighbors */
            neighbors: components["schemas"]["PageNeighbor"][];
        };
        /**
         * SourceReference
         * @description A reference to a source code location.
         */
        SourceReference: {
            /** File Path */
            file_path: string;
            /**
             * Node Id
             * @default null
             */
            node_id: string | null;
            /**
             * Line Start
             * @default null
             */
            line_start: number | null;
            /**
             * Line End
             * @default null
             */
            line_end: number | null;
            /**
             * Snippet
             * @default null
             */
            snippet: string | null;
            /**
             * Symbol
             * @default null
             */
            symbol: string | null;
            /**
             * Symbol Type
             * @default null
             */
            symbol_type: string | null;
            /**
             * Relevance Score
             * @default null
             */
            relevance_score: number | null;
            /**
             * Wiki Id
             * @default null
             */
            wiki_id: string | null;
            /**
             * Wiki Title
             * @default null
             */
            wiki_title: string | null;
            /**
             * Confidence
             * @default null
             */
            confidence: string | null;
        };
        /**
         * UpdateWikiDescriptionRequest
         * @description Request to update the description of a wiki.
         */
        UpdateWikiDescriptionRequest: {
            /** Description */
            description?: string | null;
        };
        /**
         * UpdateWikiVisibilityRequest
         * @description Request to update the visibility of a wiki.
         */
        UpdateWikiVisibilityRequest: {
            /** Visibility */
            visibility: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WikiListResponse
         * @description Response listing all wikis.
         */
        WikiListResponse: {
            /** Wikis */
            wikis?: components["schemas"]["WikiSummary"][];
        };
        /**
         * WikiPageListResponse
         * @description Response listing all pages in a wiki.
         */
        WikiPageListResponse: {
            /** Wiki Id */
            wiki_id: string;
            /** Pages */
            pages: components["schemas"]["PageListItem"][];
        };
        /**
         * WikiPageResponse
         * @description Response containing full content of a single wiki page.
         */
        WikiPageResponse: {
            /** Wiki Id */
            wiki_id: string;
            /** Page Title */
            page_title: string;
            /** Content */
            content: string;
            /** Sections */
            sections: string[];
        };
        /**
         * WikiSearchResponse
         * @description Response for a search scoped to a single wiki.
         */
        WikiSearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchResultItem"][];
            /** Wiki Summary */
            wiki_summary: components["schemas"]["WikiSummaryItem"][];
        };
        /**
         * WikiSummary
         * @description Summary of a generated wiki.
         */
        WikiSummary: {
            /** Wiki Id */
            wiki_id: string;
            /** Repo Url */
            repo_url: string;
            /** Branch */
            branch: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Page Count */
            page_count: number;
            /**
             * Status
             * @default complete
             */
            status: string;
            /**
             * Progress
             * @default 1
             */
            progress: number;
            /**
             * Invocation Id
             * @default null
             */
            invocation_id: string | null;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Indexed At
             * @default null
             */
            indexed_at: string | null;
            /**
             * Commit Hash
             * @default null
             */
            commit_hash: string | null;
            /**
             * Owner Id
             * @default null
             */
            owner_id: string | null;
            /**
             * Visibility
             * @default personal
             */
            visibility: string;
            /**
             * Is Owner
             * @default false
             */
            is_owner: boolean;
            /**
             * Requires Token
             * @default false
             */
            requires_token: boolean;
            /**
             * Description
             * @default null
             */
            description: string | null;
        };
        /**
         * WikiSummaryItem
         * @description Per-wiki aggregate summary within a search response.
         */
        WikiSummaryItem: {
            /** Wiki Id */
            wiki_id: string;
            /** Wiki Name */
            wiki_name: string;
            /** Match Count */
            match_count: number;
            /** Relevance */
            relevance: number;
        };
        /**
         * _ProjectCodeMapRequest
         * @description Request body for the project code-map endpoint.
         */
        _ProjectCodeMapRequest: {
            /** Question */
            question: string;
        };
        /**
         * SSEEvent
         * @description Generic SSE event wrapper.
         */
        SSEEvent: {
            /** Event */
            event: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /**
         * ProgressEvent
         * @description Progress update during wiki generation.
         */
        ProgressEvent: {
            /**
             * Event
             * @default progress
             */
            event: string;
            /** Phase */
            phase: string;
            /** Progress */
            progress: number;
            /** Message */
            message: string;
            /**
             * Page Id
             * @default null
             */
            page_id: string | null;
        };
        /**
         * PageCompleteEvent
         * @description Fired when a single wiki page finishes generating.
         */
        PageCompleteEvent: {
            /**
             * Event
             * @default page_complete
             */
            event: string;
            /** Page Id */
            page_id: string;
            /** Page Title */
            page_title: string;
        };
        /**
         * WikiCompleteEvent
         * @description Fired when the entire wiki generation is done.
         */
        WikiCompleteEvent: {
            /**
             * Event
             * @default wiki_complete
             */
            event: string;
            /** Wiki Id */
            wiki_id: string;
            /** Page Count */
            page_count: number;
            /** Execution Time */
            execution_time: number;
        };
        /**
         * ErrorEvent
         * @description Fired on error during generation.
         */
        ErrorEvent: {
            /**
             * Event
             * @default error
             */
            event: string;
            /** Error */
            error: string;
            /**
             * Recoverable
             * @default false
             */
            recoverable: boolean;
            /**
             * Error Type
             * @default null
             */
            error_type: string | null;
            /**
             * Model Limit
             * @default null
             */
            model_limit: number | null;
            /**
             * Suggested Actions
             * @default null
             */
            suggested_actions: string[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    generate_wiki_api_v1_generate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateWikiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateWikiResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_wikis_api_v1_wikis_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_wiki_api_v1_wikis_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateWikiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateWikiResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    scan_source_api_v1_sources_scan_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitScanRequest"] | components["schemas"]["ConfluenceScanRequest"] | components["schemas"]["JiraScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invocation_api_v1_invocations__invocation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                invocation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invocation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_invocation_api_v1_invocations__invocation_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                invocation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_invocation_api_v1_invocations__invocation_id__stream_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                invocation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_v1_ask_post: {
        parameters: {
            query?: {
                accept?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_api_v1_research_post: {
        parameters: {
            query?: {
                accept?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wiki_api_v1_wikis__wiki_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_wiki_api_v1_wikis__wiki_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteWikiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_wiki_api_v1_wikis__wiki_id__search_get: {
        parameters: {
            query: {
                q: string;
                hop_depth?: number;
                top_k?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_wiki_pages_api_v1_wikis__wiki_id__pages_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPageListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_neighbors_api_v1_wikis__wiki_id__pages__page_title__neighbors_get: {
        parameters: {
            query?: {
                hop_depth?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
                page_title: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageNeighborsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wiki_page_by_title_api_v1_wikis__wiki_id__pages__page_title__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
                page_title: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wiki_page_api_v1_wikis__wiki_id__pages__page_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_wiki_api_v1_wikis__wiki_id__resume_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateWikiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_qa_api_v1_wikis__wiki_id__qa_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: ("pending" | "validated" | "rejected" | "enriched" | "stale") | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QAListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    qa_stats_api_v1_wikis__wiki_id__qa_stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QAStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_wiki_api_v1_wikis__wiki_id__refresh_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshWikiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateWikiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_wiki_api_v1_wikis__wiki_id__diff_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiffWikiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffWikiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incremental_refresh_wiki_api_v1_wikis__wiki_id__incremental_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncrementalRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncrementalRefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_wiki_visibility_api_v1_wikis__wiki_id__visibility_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWikiVisibilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_wiki_description_api_v1_wikis__wiki_id__description_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWikiDescriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_wiki_api_v1_wikis__wiki_id__export_get: {
        parameters: {
            query?: {
                /** @description Export format: 'obsidian' or 'wikis' */
                format?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/zip": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    import_wiki_api_v1_wikis_import_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_wiki_api_v1_wikis_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiSummary"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_wikis_api_v1_projects__project_id__wikis_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_wiki_to_project_api_v1_projects__project_id__wikis_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectAddWikiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_wiki_from_project_api_v1_projects__project_id__wikis__wiki_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
                wiki_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_project_route_api_v1_projects__project_id__recompute_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_project_api_v1_projects__project_id__search_get: {
        parameters: {
            query: {
                q: string;
                hop_depth?: number;
                top_k?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_codemap_api_v1_projects__project_id__map_post: {
        parameters: {
            query?: {
                accept?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_ProjectCodeMapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
